"""thiep-test

Revision ID: c111e6d13adc
Revises: 
Create Date: 2026-01-05 14:20:03.608335+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c111e6d13adc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Internal filename'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='Original filename'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='Storage path'),
    sa.Column('size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='File description'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Public access'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='Download count'),
    sa.Column('shared_with', postgresql.ARRAY(sa.UUID()), nullable=False, comment='Shared with user IDs'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.PrimaryKeyConstraint('id'),
    schema='file_schema'
    )
    op.create_index(op.f('ix_file_schema_files_is_deleted'), 'files', ['is_deleted'], unique=False, schema='file_schema')
    op.create_index(op.f('ix_file_schema_files_is_public'), 'files', ['is_public'], unique=False, schema='file_schema')
    op.create_index(op.f('ix_file_schema_files_mime_type'), 'files', ['mime_type'], unique=False, schema='file_schema')
    op.create_index(op.f('ix_file_schema_files_name'), 'files', ['name'], unique=True, schema='file_schema')
    op.create_index(op.f('ix_file_schema_files_owner_id'), 'files', ['owner_id'], unique=False, schema='file_schema')
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique event ID'),
    sa.Column('aggregate_id', sa.UUID(), nullable=False, comment='ID of the aggregate that generated this event'),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False, comment='Type of aggregate (e.g., User, File)'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Type of event (e.g., UserCreatedEvent)'),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON serialized event data'),
    sa.Column('status', postgresql.ENUM('pending', 'published', 'failed', name='outboxeventstatus'), nullable=False, comment='Current processing status'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of publish attempts'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Maximum retry attempts'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When the event was created'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='When the event was successfully published'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False, comment='When to next attempt publishing'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message if failed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_type'), 'outbox_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_scheduled_at'), 'outbox_events', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Unique username'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='User first name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='User last name'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.PrimaryKeyConstraint('id'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_users_email'), 'users', ['email'], unique=True, schema='user_schema')
    op.create_index(op.f('ix_user_schema_users_is_active'), 'users', ['is_active'], unique=False, schema='user_schema')
    op.create_index(op.f('ix_user_schema_users_is_deleted'), 'users', ['is_deleted'], unique=False, schema='user_schema')
    op.create_index(op.f('ix_user_schema_users_username'), 'users', ['username'], unique=True, schema='user_schema')
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.ForeignKeyConstraint(['user_id'], ['user_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_user_profiles_is_deleted'), 'user_profiles', ['is_deleted'], unique=False, schema='user_schema')
    op.create_table('user_sessions',
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_token'),
    schema='user_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sessions', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_user_profiles_is_deleted'), table_name='user_profiles', schema='user_schema')
    op.drop_table('user_profiles', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_users_username'), table_name='users', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_users_is_deleted'), table_name='users', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_users_is_active'), table_name='users', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_users_email'), table_name='users', schema='user_schema')
    op.drop_table('users', schema='user_schema')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_scheduled_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_file_schema_files_owner_id'), table_name='files', schema='file_schema')
    op.drop_index(op.f('ix_file_schema_files_name'), table_name='files', schema='file_schema')
    op.drop_index(op.f('ix_file_schema_files_mime_type'), table_name='files', schema='file_schema')
    op.drop_index(op.f('ix_file_schema_files_is_public'), table_name='files', schema='file_schema')
    op.drop_index(op.f('ix_file_schema_files_is_deleted'), table_name='files', schema='file_schema')
    op.drop_table('files', schema='file_schema')
    # ### end Alembic commands ###